apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: whiskey-analytics-dag
  namespace: argo
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    entrypoint: whiskey-analytics-dag
    ttlStrategy:
      secondsAfterSuccess: 360
      secondsAfterFailure: 360
    serviceAccountName: argo-argo-workflows-server
    templates:
      - name: whiskey-analytics-dag
        dag:
          failFast: true
          tasks:
            - name: check-bucket-submittable
              templateRef:
                template: check-bucket-template
                name: check-bucket-submittable

            - name: whiskey-extractor-submittable
              templateRef:
                template: whiskey-extractor-template
                name: whiskey-extractor-submittable
              dependencies: ["check-bucket-submittable"]

            - name: print-success-submittable
              templateRef:
                template: print-success-template
                name: print-success-submittable
              dependencies: ["check-bucket-submittable", "whiskey-extractor-submittable"]
